/**
 * What the directory walk hands the engines.
 *
 * The walk used to read every scannable file under a target, including the
 * build-output trees a project regenerates. Those trees hold copies: one
 * bundled stylesheet reproduced into every artifact directory reports the same
 * declarations once per copy, so a single source line reached the report
 * hundreds of times and the volume buried everything the walk had to say about
 * the sources a human can edit.
 *
 * Deciding what is generated is not this module's question and is not answered
 * here: `.claude/skills/frontend-design/scripts/lib/is-generated.mjs` answers
 * it, for the editor surface as well as for the walk, and the walk consults it.
 *
 * The repository runs this file automatically; which files it runs is decided
 * by node's own test-file naming convention over the skill tree. Nothing else
 * reaches them — `.claude/**` is outside every workspace glob, so no vitest
 * project and no ESLint config sees them. Run them on their own with
 * `node --test` from the repository root.
 */

import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { generatedFilesAmong } from '../../lib/is-generated.mjs';
import { walkDir, walkScope } from './file-system.mjs';

const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'detector-walk-'));
test.after(() => fs.rmSync(scratch, { recursive: true, force: true }));

let caseCount = 0;

/**
 * A directory holding the given files, outside any git work tree, so the only
 * signal that can decide anything about it is the one written into a file.
 * @param {Record<string, string>} files
 */
function tree(files) {
  const root = path.join(scratch, `case-${++caseCount}`);
  for (const [relative, content] of Object.entries(files)) {
    const full = path.join(root, relative);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  }
  return root;
}

/** @param {string} root */
function walkedNames(root) {
  return walkDir(root)
    .map((file) => path.relative(root, file))
    .sort();
}

test('the walk reads a source file', () => {
  const root = tree({ 'src/app.css': '.a { color: red }' });
  assert.deepEqual(walkedNames(root), [path.join('src', 'app.css')]);
});

test('the walk leaves out a file whose header says it is generated', () => {
  const root = tree({
    'src/app.css': '.a { color: red }',
    'src/bundle.css': '/* @generated by the bundler */\n.a { color: red }',
  });
  assert.deepEqual(walkedNames(root), [path.join('src', 'app.css')]);
});

// The other signal `is-generated.mjs` reads is git's own answer, which needs a
// work tree to answer against — so it is driven against this repository's,
// where the ignore rules are the ones the walk meets in use. `git check-ignore`
// answers about a path rather than about a file on disk, so no fixture is
// written anywhere to ask it.
const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  '..',
  '..',
  '..',
  '..'
);

test('a git-ignored path is generated and a tracked one is not', () => {
  const ignored = path.join(REPO_ROOT, 'node_modules', '.cache', 'sample.css');
  const tracked = path.join(
    REPO_ROOT,
    '.claude/skills/frontend-design/scripts/detector/test-fixtures/component-styles.css'
  );
  assert.ok(fs.existsSync(tracked), 'positive control: the tracked fixture must exist');
  assert.deepEqual(generatedFilesAmong([ignored, tracked], { cwd: REPO_ROOT }), new Set([ignored]));
});

test('one path being ignored does not make its neighbours ignored', () => {
  const tracked = path.join(
    REPO_ROOT,
    '.claude/skills/frontend-design/scripts/detector/test-fixtures/marketing-page.html'
  );
  assert.deepEqual(generatedFilesAmong([tracked], { cwd: REPO_ROOT }), new Set());
});

// What the walk left out is the walk's own answer, not something a caller can
// re-derive: it is the difference between the files a directory holds and the
// files the walk hands on, and by the time a caller sees the second the first
// is gone. A caller that cannot say how much it skipped can only report a short
// scan as a clean one.

test('the walk reports the generated files it left out', () => {
  const root = tree({
    'src/app.css': '.a { color: red }',
    'src/bundle.css': '/* @generated by the bundler */\n.a { color: red }',
  });
  assert.deepEqual(
    walkScope(root).generated.map((file) => path.relative(root, file)),
    [path.join('src', 'bundle.css')]
  );
});

test('the walk reports nothing left out where nothing is generated', () => {
  const root = tree({ 'src/app.css': '.a { color: red }' });
  const scope = walkScope(root);
  assert.deepEqual(scope.generated, []);
  assert.deepEqual(scope.files.map((file) => path.relative(root, file)), [path.join('src', 'app.css')]);
});
