/**
 * A long-context threshold means "above this many prompt tokens", and a tier
 * above 0 applies to every request with a prompt, which makes it a second base
 * price rather than a tier. The descriptor schema and the served wire therefore
 * agree: each accepts a threshold exactly when it is positive, so no stored
 * threshold can make a row the model list then refuses to serve.
 *
 * The ceiling a hold reserves at never falls below the anchor it is derived
 * from at any prompt size, and each of its rates is the least whole nano at or
 * above five quarters of the anchor's rate at the same tier.
 */

import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { modelSchema } from '../../schemas/api/models.ts';
import { nanoUSD } from '../money/nano-usd.ts';
import { ceilingOf, ModelPricingSchema, resolveTier } from './schedule.ts';
import type { TokenPriceSchedule, TokenRates } from './schedule.ts';

/** A threshold either side of the boundary: 0 and 1 always in reach, and integers around them. */
const thresholdArb = fc.oneof(fc.constantFrom(0, 1), fc.integer({ min: -1000, max: 1_000_000 }));

function descriptorAccepts(abovePromptTokens: number): boolean {
  return ModelPricingSchema.safeParse({
    kind: 'tokens',
    anchor: {
      base: { input: '3450', output: '17250' },
      tiers: [{ abovePromptTokens, rates: { input: '6900', output: '25875' } }],
    },
  }).success;
}

function wireAccepts(abovePromptTokens: number): boolean {
  return modelSchema.safeParse({
    id: 'vendor/model',
    name: 'Vendor Model',
    provider: 'vendor',
    modality: 'text',
    contextLength: 1_000_000,
    pricing: {
      inputPerToken: '3450',
      outputPerToken: '17250',
      longContextRates: [{ abovePromptTokens, inputPerToken: '6900', outputPerToken: '25875' }],
    },
    description: 'a model',
  }).success;
}

describe('a long-context threshold, generated by thresholdArb', () => {
  it('is accepted by the descriptor schema exactly when it is positive', () => {
    fc.assert(
      fc.property(thresholdArb, (threshold) => {
        expect(descriptorAccepts(threshold)).toBe(threshold > 0);
      })
    );
  });

  it('is accepted by the served wire exactly when it is positive', () => {
    fc.assert(
      fc.property(thresholdArb, (threshold) => {
        expect(wireAccepts(threshold)).toBe(threshold > 0);
      })
    );
  });
});

/** A positive billable rate, from one nano to past any live rate. */
const rateArb = fc.bigInt({ min: 1n, max: 10n ** 12n });

/** Rates that never fall below `below`: each is `below`'s plus a non-negative step. */
function ratesAtLeast(below: TokenRates): fc.Arbitrary<TokenRates> {
  return fc
    .record({ input: fc.bigInt({ min: 0n, max: 10n ** 12n }), output: fc.bigInt({ min: 0n, max: 10n ** 12n }) })
    .map((step) => ({
      input: nanoUSD(below.input + step.input),
      output: nanoUSD(below.output + step.output),
    }));
}

/**
 * An anchor schedule as the schema admits one: positive base rates, and up to
 * three tiers at strictly ascending positive thresholds whose rates never fall
 * below the rates beneath them.
 */
const anchorScheduleArb: fc.Arbitrary<TokenPriceSchedule> = fc
  .record({
    base: fc.record({ input: rateArb, output: rateArb }),
    thresholds: fc.uniqueArray(fc.integer({ min: 1, max: 2_000_000 }), { maxLength: 3 }),
  })
  .chain(({ base, thresholds }) => {
    const baseRates: TokenRates = { input: nanoUSD(base.input), output: nanoUSD(base.output) };
    const ascending = thresholds.toSorted((a, b) => a - b);
    let tiers: fc.Arbitrary<TokenPriceSchedule['tiers']> = fc.constant([]);
    for (const abovePromptTokens of ascending) {
      tiers = tiers.chain((built) =>
        ratesAtLeast(built.at(-1)?.rates ?? baseRates).map((rates) => [
          ...built,
          { abovePromptTokens, rates },
        ])
      );
    }
    return tiers.map((built) => ({ base: baseRates, tiers: built }));
  });

/** A prompt token count from empty to past every generated threshold. */
const promptTokensArb = fc.integer({ min: 0, max: 2_500_000 });

describe('the ceiling of an anchor schedule, generated by anchorScheduleArb', () => {
  it('is no cheaper than the anchor at any prompt size, drawn by promptTokensArb', () => {
    fc.assert(
      fc.property(anchorScheduleArb, promptTokensArb, (anchor, promptTokens) => {
        const atAnchor = resolveTier(anchor, promptTokens);
        const atCeiling = resolveTier(ceilingOf(anchor), promptTokens);
        expect(atCeiling.tier).toBe(atAnchor.tier);
        expect(atCeiling.rates.input >= atAnchor.rates.input).toBe(true);
        expect(atCeiling.rates.output >= atAnchor.rates.output).toBe(true);
      })
    );
  });

  it('holds each rate at the least whole nano at or above five quarters of the anchor rate at its tier', () => {
    fc.assert(
      fc.property(anchorScheduleArb, (anchor) => {
        const ceiling = ceilingOf(anchor);
        const pairs: [bigint, bigint][] = [
          [anchor.base.input, ceiling.base.input],
          [anchor.base.output, ceiling.base.output],
        ];
        expect(ceiling.tiers.map((tier) => tier.abovePromptTokens)).toEqual(
          anchor.tiers.map((tier) => tier.abovePromptTokens)
        );
        for (const [index, tier] of anchor.tiers.entries()) {
          const held = ceiling.tiers[index]!.rates;
          pairs.push([tier.rates.input, held.input], [tier.rates.output, held.output]);
        }
        for (const [anchorRate, ceilingRate] of pairs) {
          expect(4n * ceilingRate >= 5n * anchorRate).toBe(true);
          expect(4n * (ceilingRate - 1n) < 5n * anchorRate).toBe(true);
        }
      })
    );
  });
});
