/**
 * The served wire loses nothing a price holds. A descriptor's price, served
 * through {@link pricingToWire} and parsed back off the row the schema accepts,
 * is the price it was: every long-context tier of a token schedule, and both
 * sides of a media price, including a dearest side above its anchor.
 */

import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { modelSchema } from '../../schemas/api/models.ts';
import {
  perImagePricingFixture,
  perSecondPricingFixture,
  tokenPricingFixture,
} from '../../testing/pricing-fixture.ts';
import { pricingFromWire, pricingToWire } from './wire.ts';
import type { ModelPricing } from './schedule.ts';

/** A positive billable nano rate, small to large. */
const rateArb = fc.bigInt({ min: 1n, max: 10n ** 12n });

/** A rate and one no smaller, as a dearest side sits over its anchor. */
const orderedPairArb = fc
  .tuple(rateArb, fc.bigInt({ min: 0n, max: 10n ** 12n }))
  .map(([anchor, extra]) => ({ anchor, dearest: anchor + extra }));

/**
 * A token schedule: base rates and zero to three tiers at strictly ascending
 * thresholds, each tier's rates no lower than the rates beneath it.
 */
const tieredTokenPricingArb = fc
  .record({
    input: rateArb,
    output: rateArb,
    steps: fc.array(
      fc.record({
        gap: fc.integer({ min: 1, max: 400_000 }),
        inputRise: fc.bigInt({ min: 0n, max: 10n ** 9n }),
        outputRise: fc.bigInt({ min: 0n, max: 10n ** 9n }),
      }),
      { maxLength: 3 }
    ),
  })
  .map(({ input, output, steps }) => {
    let abovePromptTokens = 0;
    let tierInput = input;
    let tierOutput = output;
    const tiers = steps.map((step) => {
      abovePromptTokens += step.gap;
      tierInput += step.inputRise;
      tierOutput += step.outputRise;
      return { abovePromptTokens, input: tierInput, output: tierOutput };
    });
    return tokenPricingFixture({ input, output, tiers });
  });

const RESOLUTIONS = ['480p', '720p', '1080p', '4k'] as const;

/** A per-second price: one to four resolutions, each dearest at or above its anchor. */
const perSecondPricingArb = fc
  .uniqueArray(fc.constantFrom(...RESOLUTIONS), { minLength: 1, maxLength: RESOLUTIONS.length })
  .chain((resolutions) =>
    fc
      .array(orderedPairArb, { minLength: resolutions.length, maxLength: resolutions.length })
      .map((pairs) =>
        perSecondPricingFixture({
          anchor: Object.fromEntries(
            resolutions.map((resolution, index) => [resolution, pairs[index]!.anchor])
          ),
          dearest: Object.fromEntries(
            resolutions.map((resolution, index) => [resolution, pairs[index]!.dearest])
          ),
        })
      )
  );

/** A descriptor's price of any kind, with the modality the served row carries for it. */
const tieredDescriptorArb: fc.Arbitrary<{
  readonly modality: 'text' | 'image' | 'video';
  readonly pricing: ModelPricing;
}> = fc.oneof(
  tieredTokenPricingArb.map((pricing) => ({ modality: 'text' as const, pricing })),
  orderedPairArb.map((pair) => ({
    modality: 'image' as const,
    pricing: perImagePricingFixture(pair),
  })),
  perSecondPricingArb.map((pricing) => ({ modality: 'video' as const, pricing }))
);

describe('the served wire, generated by tieredDescriptorArb', () => {
  it('parses back to the descriptor’s own price', () => {
    fc.assert(
      fc.property(tieredDescriptorArb, ({ modality, pricing }) => {
        const row = modelSchema.parse({
          id: 'vendor/model',
          name: 'Vendor Model',
          provider: 'vendor',
          modality,
          contextLength: modality === 'text' ? 1_000_000 : 0,
          pricing: pricingToWire(pricing),
          description: 'a model',
        });

        expect(pricingFromWire(row)).toEqual(pricing);
      })
    );
  });
});
