import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { planReasoning, reasoningPlanModelFrom } from '@hushbox/shared';
import {
  deriveCiVitestGate,
  deriveIntegrationEnv,
  languageDescriptor,
  languageRequest,
  processEnvContext,
  reasoningBudgetDescriptor,
  reasoningBudgetRequest,
  reasoningEffortRequest,
  reasoningOffRequest,
  setupIntegrationProvider,
  useIntegrationProvider,
} from './integration.setup.js';
import {
  beginCassetteScope,
  createCassetteFetch,
  endCassetteScope,
} from './cassette/recording-fetch.js';
import { createCassetteStore } from './cassette/cassette-store.js';
import type { InferenceEvent } from '@hushbox/shared';

/**
 * Harness-side pin for the env→provider derivation: the adapter integration
 * suites resolve the deterministic mock everywhere the environment is not the
 * credentialled continuous-integration one — the structural guarantee that no
 * shell generated for a mock run can make a real evidence-writing OpenRouter
 * call. Every case states an environment, so the pin holds identically in
 * every phase.
 */
describe('deriveIntegrationEnv', () => {
  it('yields the mock outside CI (local vitest shell)', () => {
    expect(deriveIntegrationEnv({ NODE_ENV: 'development', VITEST: 'true' })).toEqual({
      useMock: true,
      isCI: false,
    });
  });

  it('yields the mock for an E2E-shaped shell without CI', () => {
    expect(deriveIntegrationEnv({ NODE_ENV: 'development', E2E: 'true', VITEST: 'true' })).toEqual({
      useMock: true,
      isCI: false,
    });
  });

  it('yields the real path for a CI, non-E2E shell', () => {
    expect(deriveIntegrationEnv({ NODE_ENV: 'development', CI: 'true', VITEST: 'true' })).toEqual({
      useMock: false,
      isCI: true,
    });
  });
});

/**
 * Pin for the CI-vitest real-call gate the still-skipping real-only suites
 * (gateway-metadata) derive `SHOULD_RUN` from: a real OpenRouter call is
 * reachable only from a CI, non-E2E environment — never from a local shell,
 * however its other vars look.
 */
describe('deriveCiVitestGate', () => {
  it('refuses a local vitest shell', () => {
    expect(deriveCiVitestGate({ NODE_ENV: 'development', VITEST: 'true' })).toBe(false);
  });

  it('refuses a CI-E2E shell', () => {
    expect(
      deriveCiVitestGate({ NODE_ENV: 'development', CI: 'true', E2E: 'true', VITEST: 'true' })
    ).toBe(false);
  });

  it('admits CI-vitest', () => {
    expect(deriveCiVitestGate({ NODE_ENV: 'development', CI: 'true', VITEST: 'true' })).toBe(true);
  });
});

/**
 * The placeholder credential's pin, taken through the ambient reader rather
 * than a hand-built context, because the claim is about what a real process
 * presents. A run whose configuration carries the placeholder was generated by
 * a mode that states no continuous-integration flag, and the loader deletes
 * every classification variable its generating mode leaves unstated — so that
 * process presents a non-CI classification even on a runner that sets the flag
 * itself, and the harness resolves the mock. The pair moves together: the
 * environment carrying the placeholder is the environment that fails the gate.
 */
describe('processEnvContext — the placeholder-carrying environment', () => {
  /** What `vi.stubEnv` takes to delete a variable rather than give it a value. */
  const UNSET = undefined;

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it('resolves the mock for a process carrying the development placeholder credential', () => {
    vi.stubEnv('OPENROUTER_API_KEY', 'mock-openrouter-key');
    vi.stubEnv('NODE_ENV', 'development');
    vi.stubEnv('CI', UNSET);
    vi.stubEnv('E2E', UNSET);

    expect(deriveIntegrationEnv(processEnvContext())).toEqual({ useMock: true, isCI: false });
  });

  /**
   * The closed fail-open: an absent credential used to subtract a term from
   * the gate, silently selecting the mock and letting the real-provider
   * assertions skip while the suite passed. It now throws before anything is
   * constructed.
   */
  it('throws on the real path when the credential is absent, rather than selecting the mock', () => {
    vi.stubEnv('OPENROUTER_API_KEY', '');

    expect(() =>
      setupIntegrationProvider({ NODE_ENV: 'development', CI: 'true', VITEST: 'true' })
    ).toThrow('OPENROUTER_API_KEY is required');
  });
});

/**
 * The gate on the bare door. `setupIntegrationProvider` hands back a provider
 * to whoever asks, while the occurrence scope that keeps a repeated request off
 * the live gateway rides on {@link useIntegrationProvider}. A suite reaching
 * past the lifecycle would therefore hold a working, unscoped provider, and its
 * second identical request keys past its recording into a charged generation on
 * the credentialled path — invisible until the bill. The provider refuses that
 * call instead, and refuses it on the mock path too, so the machine that would
 * have spent nothing is the one that goes red.
 */
describe('setupIntegrationProvider — outside any occurrence scope', () => {
  it('refuses to infer and names the lifecycle the caller must take', async () => {
    const setup = setupIntegrationProvider({ NODE_ENV: 'development', VITEST: 'true' });

    expect(() => setup.provider.infer(languageRequest(), languageDescriptor())).toThrow(
      'useIntegrationProvider'
    );

    await setup.teardown();
  });
});

describe('setupIntegrationProvider — mock path', () => {
  // The provider refuses outside an occurrence scope. This case is about the
  // mock derivation rather than about a suite lifecycle, so it opens one
  // directly instead of taking `useIntegrationProvider`.
  beforeEach(() => {
    beginCassetteScope();
  });

  afterEach(() => {
    endCassetteScope();
  });

  it('resolves the deterministic mock outside CI and its teardown is a no-op', async () => {
    const setup = setupIntegrationProvider({ NODE_ENV: 'development', VITEST: 'true' });
    const events: InferenceEvent[] = [];
    for await (const event of setup.provider.infer(languageRequest(), languageDescriptor())) {
      events.push(event);
    }
    const text = events
      .filter((event) => event.kind === 'text-delta')
      .map((event) => event.content)
      .join('');
    expect(text).toContain('Echo:');
    await expect(setup.teardown()).resolves.toBeUndefined();
  });
});

/**
 * The money guard on the suite lifecycle. A suite's cassette closure lives for
 * the whole file and keys a repeated request by its occurrence, so two tests
 * issuing byte-identical requests would key the second past its recording,
 * miss, and reach the live gateway — on the credentialled path a second
 * charged generation, which for video is a whole second one. What prevents it
 * is the scope {@link useIntegrationProvider} opens before every test, and this
 * drives the pair through that lifecycle rather than calling the reset: the
 * request is recorded once in `beforeAll`, and each test then repeats it and
 * asserts the gateway was not called again. Dropping the hook turns this red on
 * any machine, before CI spends anything — which is the whole reason the reset
 * rides on the harness door rather than on each suite remembering it.
 */
describe('useIntegrationProvider — the cassette scope around each test', () => {
  // Taken for its lifecycle alone; this suite needs no provider, and the
  // accessor is lazy, so nothing is constructed here.
  useIntegrationProvider();

  const GATEWAY_REQUEST: [string, RequestInit] = [
    'https://openrouter.ai/api/v1/chat/completions',
    {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ model: 'openai/gpt-4o', prompt: 'the same bytes twice' }),
    },
  ];

  let rootDir: string;
  let gatewayCalls: number;
  let cassetteFetch: typeof globalThis.fetch;

  beforeAll(async () => {
    rootDir = mkdtempSync(path.join(tmpdir(), 'integration-setup-scope-'));
    gatewayCalls = 0;
    // A hand-rolled counter rather than `vi.fn`: the shared config resets mocks
    // before every test, so a mock's call count cannot carry a claim across the
    // test boundary this suite is about. Each call answers a distinct body, so
    // a live call is visible in what the caller received, not only in a count.
    const gateway = (): Promise<Response> => {
      gatewayCalls += 1;
      return Promise.resolve(
        new Response(`{"call":${gatewayCalls.toString()}}`, {
          status: 200,
          headers: { 'content-type': 'application/json' },
        })
      );
    };
    cassetteFetch = createCassetteFetch({
      store: createCassetteStore({ rootDir }),
      mode: 'record',
      realFetch: gateway as unknown as typeof globalThis.fetch,
    });
    const recorded = await cassetteFetch(...GATEWAY_REQUEST);
    await recorded.text();
  });

  afterAll(() => {
    rmSync(rootDir, { recursive: true, force: true });
  });

  it('replays the recording rather than calling the gateway again', async () => {
    const response = await cassetteFetch(...GATEWAY_REQUEST);

    expect(await response.text()).toBe('{"call":1}');
    expect(gatewayCalls).toBe(1);
  });

  it('replays it again in the next test, so the scope opens per test and not once', async () => {
    const response = await cassetteFetch(...GATEWAY_REQUEST);

    expect(await response.text()).toBe('{"call":1}');
    expect(gatewayCalls).toBe(1);
  });
});

/**
 * The reasoning request bodies are cassette keys: the canonical body bytes
 * feed the recording hash, so a silent move in the shared plan's output
 * orphans both recordings and buys a real charged call on the next CI run.
 * These pin the exact wire numbers, which no green local run can observe —
 * the local provider is the deterministic mock.
 */
describe('reasoning request bodies — cassette-bearing wire values', () => {
  it('wires the low rung at its full 4096-token budget for the effort-native model', () => {
    expect(reasoningEffortRequest().parameters).toEqual({
      reasoning: { effort: 'low' },
      maxOutputTokens: 4608,
    });
  });

  it('wires the low rung at its full 4096-token budget for the budget-native model', () => {
    expect(reasoningBudgetRequest().parameters).toEqual({
      reasoning: { max_tokens: 4096 },
      maxOutputTokens: 4608,
    });
  });

  it('spends the whole completion cap on the answer under the hard-off wire', () => {
    expect(reasoningOffRequest().parameters).toEqual({
      reasoning: { enabled: false },
      maxOutputTokens: 512,
    });
  });
});

/**
 * The top rung's tier (65,536) is one token above what the budget-native model
 * accepts, so a descriptor that declared no completion ceiling would wire a
 * budget the gateway rejects the moment anything climbs there. The ceiling is
 * the model's real one, and this pins the rung the ceiling clamps; the
 * headroom is the smallest legal one so the assertion is about the clamp alone.
 */
describe('reasoning descriptor completion ceilings', () => {
  it('clamps the budget-native max rung to the ceiling the model accepts', () => {
    const result = planReasoning(reasoningPlanModelFrom(reasoningBudgetDescriptor()), 'max', 1);

    expect(result).toEqual({
      feasible: true,
      plan: {
        reasoningBudgetTokens: 65_535,
        answerHeadroomTokens: 1,
        maxTokens: 65_536,
        wire: { max_tokens: 65_535 },
        level: 'max',
      },
    });
  });
});
