name: 'Setup (Blacksmith)'
description: 'Setup Node.js, pnpm with Blacksmith-optimized caching'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.26.0

    - uses: useblacksmith/setup-node@v5
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
