/**
 * Single source of truth for this app's `data-testid` values. A literal
 * `data-testid` string anywhere in `src/**` is a lint error, so every id a
 * component emits is added here first.
 *
 * Keys are camelCase; values are the literal kebab-case `data-testid`.
 */
export const TEST_IDS = {
  consoleRoot: 'console-root',
  consoleErrorFallback: 'console-error-fallback',
  consoleShell: 'console-shell',
  auditSwitcher: 'audit-switcher',
  sectionNav: 'section-nav',
  searchInput: 'search-input',
  filterRail: 'filter-rail',
  areaFilter: 'area-filter',
  findingList: 'finding-list',
  findingRow: 'finding-row',
  focusedFinding: 'focused-finding',
  validationBanner: 'validation-banner',
  findingCard: 'finding-card',
  decisionSummary: 'decision-summary',
  blockedStamp: 'blocked-stamp',
  blockingNote: 'blocking-note',
  blockingReplies: 'blocking-replies',
  findingChip: 'finding-chip',
  optionChoice: 'option-choice',
  dedicatedBanner: 'dedicated-banner',
  dedicatedToggle: 'dedicated-toggle',
  unblockDedicated: 'unblock-dedicated',
  optionNote: 'option-note',
  promptInput: 'prompt-input',
  writeError: 'write-error',
  findingPalette: 'finding-palette',
  paletteInput: 'palette-input',
  paletteOption: 'palette-option',
  dashboardPane: 'dashboard-pane',
  dashboardAwaiting: 'dashboard-awaiting',
  dashboardSettled: 'dashboard-settled',
  dashboardDecided: 'dashboard-decided',
  dashboardBlocked: 'dashboard-blocked',
  dashboardDedicated: 'dashboard-dedicated',
  dashboardSeverity: 'dashboard-severity',
  dashboardArea: 'dashboard-area',
  progressBoard: 'progress-board',
  progressColumn: 'progress-column',
  progressCard: 'progress-card',
  progressStatus: 'progress-status',
  progressNote: 'progress-note',
  progressError: 'progress-error',
  confirmAccept: 'confirm-accept',
  compiledQuestions: 'compiled-questions',
  compiledQuestionsCopy: 'compiled-questions-copy',
  questionWithdraw: 'question-withdraw',
  bulkActions: 'bulk-actions',
  ruledPane: 'ruled-pane',
  ruledRow: 'ruled-row',
  ruledBriefCopy: 'ruled-brief-copy',
  deniedPane: 'denied-pane',
  deniedGroup: 'denied-group',
  deniedRow: 'denied-row',
  reopenFinding: 'reopen-finding',
  paneError: 'pane-error',
  sourcePeek: 'source-peek',
  sourcePeekNotice: 'source-peek-notice',
} as const;
