/**
 * Media generation pipeline — shared orchestrator for image / video / audio.
 *
 * The three media modalities share an identical pipeline shape: fan out per-
 * model inference, collect generated bytes, encrypt with the conversation
 * epoch key, store in R2, compute exact post-flight costs, persist
 * (`saveChatTurn`), attach presigned URLs to the SSE done event, and
 * broadcast completion. Modality-specific behavior (request shape, pricing,
 * fallback message) plugs in via the `MediaModalityStrategy` descriptor.
 *
 * Lifted out of `stream-pipeline.ts` to give the orchestrator and its private
 * helpers a clean home; nothing structural changed relative to the inline
 * implementation.
 */

import { eq } from 'drizzle-orm';
import { conversations } from '@hushbox/db';
import {
  ERROR_CODE_BILLING_ERROR,
  KEEPALIVE_INTERVAL_MS,
  MEDIA_DOWNLOAD_URL_TTL_SECONDS,
  calculateMediaGenerationCost,
} from '@hushbox/shared';
import { beginMessageEnvelope, encryptBinaryWithContentKey } from '@hushbox/crypto';
import { streamSSE } from 'hono/streaming';
import { createEvent } from '@hushbox/realtime/events';
import type { Context } from 'hono';
import type { AppEnv } from '../types.js';
import type { InferenceRequest } from '../services/ai/index.js';
import type { MemberContext } from '../services/billing/index.js';
import { fetchEpochPublicKey } from '../services/chat/message-helpers.js';
import { saveChatTurn } from '../services/chat/index.js';
import type { SaveChatTurnResult } from '../services/chat/index.js';
import type { MediaAssistantMessageInput } from '../services/chat/message-persistence.js';
import type { MediaStorage } from '../services/storage/index.js';
import { broadcastFireAndForget } from './broadcast.js';
import {
  collectMultiMediaModelStreams,
  type MediaModelStreamEntry,
  type MediaStreamResult,
} from './multi-stream.js';
import { safeExecutionCtx } from './safe-execution-ctx.js';
import { createSSEEventWriter } from './stream-handler.js';
import type { GroupBudgetReservation } from './speculative-balance.js';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type { MediaPersistPricing } from './billing-types.js';
import type { MediaPersistPricing } from './billing-types.js';
import { buildGroupBillingContext } from './billing-types.js';

export interface MediaPipelineInput {
  c: Context<AppEnv>;
  conversationId: string;
  models: string[];
  userMessage: { id: string; content: string };
  prompt: string;
  billingUserId: string;
  groupBudget: GroupBudgetReservation | undefined;
  memberContext: MemberContext | undefined;
  releaseReservation: () => Promise<void>;
  senderId: string;
  forkId: string | undefined;
  parentMessageId: string | null;
  pricingFor: (modelId: string, result: MediaStreamResult) => MediaPersistPricing;
  buildRequest: (modelId: string) => InferenceRequest;
  /** Message written to SSE when every model in the batch fails. */
  noContentErrorMessage: string;
}

type SSEEventWriter = ReturnType<typeof createSSEEventWriter>;

/**
 * Writes the SSE comment line `:keep-alive\n\n` to the underlying stream.
 * Comments are spec-defined as ignored by EventSource consumers; the bytes
 * still flow through the reader and reset the client-side
 * `readWithTimeout` timer.
 *
 * Swallows write rejections — after an abort, the next typed write via
 * `writeIfConnected` learns about the disconnection through the writer's
 * `onAbort` callback.
 */
async function writeKeepAliveSafe(stream: {
  write: (s: string) => Promise<unknown>;
}): Promise<void> {
  try {
    await stream.write(':keep-alive\n\n');
  } catch {
    // Stream is closed/aborted; the typed writer will mark itself
    // disconnected on the next `writeIfConnected` call.
  }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function defaultMimeType(kind: MediaPersistPricing['kind']): string {
  switch (kind) {
    case 'image': {
      return 'image/png';
    }
    case 'video': {
      return 'video/mp4';
    }
    case 'audio': {
      return 'audio/mpeg';
    }
  }
}

/**
 * `MediaPersistPricing` extends `MediaPricing` with kind-specific extras
 * (resolution for video, durationSeconds for audio/video). The shared helper
 * in `@hushbox/shared` consumes only `pricing.kind` + the per-call params, so
 * we forward the fields it cares about and let it own the math. Keeping a
 * single switch in shared/pricing.ts means future media kinds need only one
 * addition there, not one here too.
 */
function computeMediaCost(pricing: MediaPersistPricing, sizeBytes: number): number {
  if (pricing.kind === 'image') {
    return calculateMediaGenerationCost({
      pricing: { kind: 'image', perImage: pricing.perImage },
      sizeBytes,
      imageCount: 1,
    });
  }
  return calculateMediaGenerationCost({
    pricing: { kind: pricing.kind, perSecond: pricing.perSecond },
    sizeBytes,
    durationSeconds: pricing.durationSeconds,
  });
}

interface MediaStorageRef {
  storageKey: string;
  mimeType: string;
  sizeBytes: number;
}

interface MediaDimensions {
  width: number | undefined;
  height: number | undefined;
  durationMs: number | undefined;
}

interface BuildMediaAssistantMessageInput {
  assistantMsgId: string;
  contentItemId: string;
  wrappedContentKey: Uint8Array;
  pricing: MediaPersistPricing;
  storage: MediaStorageRef;
  metadata: MediaDimensions;
  modelId: string;
  totalCost: number;
}

function buildMediaAssistantMessage(
  input: BuildMediaAssistantMessageInput
): MediaAssistantMessageInput {
  const {
    assistantMsgId,
    contentItemId,
    wrappedContentKey,
    pricing,
    storage,
    metadata,
    modelId,
    totalCost,
  } = input;
  const kind = pricing.kind;
  return {
    modality: kind,
    id: assistantMsgId,
    wrappedContentKey,
    contentItems: [
      {
        id: contentItemId,
        contentType: kind,
        position: 0,
        storageKey: storage.storageKey,
        mimeType: storage.mimeType,
        sizeBytes: storage.sizeBytes,
        ...(metadata.width !== undefined && { width: metadata.width }),
        ...(metadata.height !== undefined && { height: metadata.height }),
        ...(metadata.durationMs !== undefined && { durationMs: metadata.durationMs }),
        modelName: modelId,
        cost: totalCost.toFixed(8),
        isSmartModel: false,
      },
    ],
    model: modelId,
    cost: totalCost,
    mediaType: kind,
    ...(kind === 'image' && { imageCount: 1 }),
    ...(metadata.durationMs !== undefined && { durationMs: metadata.durationMs }),
    ...(kind === 'video' && { resolution: pricing.resolution }),
  };
}

interface EncryptAndStoreMediaResult {
  assistantMessage: MediaAssistantMessageInput;
  contentItemId: string;
  downloadUrl: string;
}

interface EncryptAndStoreMediaInput {
  mediaStorage: MediaStorage;
  epochPublicKey: Uint8Array;
  conversationId: string;
  modelId: string;
  assistantMsgId: string;
  mediaBytes: Uint8Array;
  mimeType: string | undefined;
  width: number | undefined;
  height: number | undefined;
  durationMs: number | undefined;
  pricing: MediaPersistPricing;
}

/** Encrypts a single media item (image/video/audio), stores it in R2, and returns the assistant message input. */
async function encryptAndStoreMedia(
  input: EncryptAndStoreMediaInput
): Promise<EncryptAndStoreMediaResult> {
  const {
    mediaStorage,
    epochPublicKey,
    conversationId,
    modelId,
    assistantMsgId,
    mediaBytes,
    mimeType,
    width,
    height,
    durationMs,
    pricing,
  } = input;
  const contentItemId = crypto.randomUUID();
  const storageKey = `media/${conversationId}/${assistantMsgId}/${contentItemId}.enc`;

  const { contentKey, wrappedContentKey } = beginMessageEnvelope(epochPublicKey);
  const ciphertext = encryptBinaryWithContentKey(contentKey, mediaBytes);

  await mediaStorage.put(storageKey, ciphertext, 'application/octet-stream');

  const { url: downloadUrl } = await mediaStorage.mintDownloadUrl({
    key: storageKey,
    expiresInSec: MEDIA_DOWNLOAD_URL_TTL_SECONDS,
  });

  const totalCost = computeMediaCost(pricing, ciphertext.byteLength);

  return {
    contentItemId,
    downloadUrl,
    assistantMessage: buildMediaAssistantMessage({
      assistantMsgId,
      contentItemId,
      wrappedContentKey,
      pricing,
      storage: {
        storageKey,
        mimeType: mimeType ?? defaultMimeType(pricing.kind),
        sizeBytes: ciphertext.byteLength,
      },
      metadata: { width, height, durationMs },
      modelId,
      totalCost,
    }),
  };
}

/** Attaches download URLs to media content items on a billing result for SSE serialization. */
function attachDownloadUrls(
  billingResult: SaveChatTurnResult,
  downloadUrls: Map<string, string>
): void {
  for (const assistantResult of billingResult.assistantResults) {
    if (!('contentItems' in assistantResult.envelope)) continue;
    for (const item of assistantResult.envelope.contentItems) {
      const url = downloadUrls.get(item.id);
      if (url !== undefined) item.downloadUrl = url;
    }
  }
}

/** Filters media results to only those with successful bytes. */
function filterSuccessfulMediaModels(
  mediaResults: Map<string, MediaStreamResult>
): [string, MediaStreamResult][] {
  return [...mediaResults.entries()].filter(
    ([, r]) => r.error === null && r.mediaBytes !== undefined && r.mediaBytes.length > 0
  );
}

interface ProcessMediaResultsInput {
  mediaStorage: MediaStorage;
  epochPublicKey: Uint8Array;
  conversationId: string;
  /**
   * Per-result pricing factory — called once per successful model result.
   * Receives the result so audio can derive `durationSeconds` from
   * `result.durationMs`. Image/video implementations ignore the second arg.
   */
  pricingFor: (modelId: string, result: MediaStreamResult) => MediaPersistPricing;
  getAssistantId: (modelId: string) => string;
  successfulModels: [string, MediaStreamResult][];
}

interface ProcessMediaResultsOutput {
  assistantMessages: MediaAssistantMessageInput[];
  downloadUrls: Map<string, string>;
}

/** Encrypts and stores media for all successful models, returning assistant messages and download URLs. */
async function processMediaResults(
  input: ProcessMediaResultsInput
): Promise<ProcessMediaResultsOutput> {
  const {
    mediaStorage,
    epochPublicKey,
    conversationId,
    pricingFor,
    getAssistantId,
    successfulModels,
  } = input;

  const assistantMessages: MediaAssistantMessageInput[] = [];
  const downloadUrls = new Map<string, string>();

  for (const [modelId, result] of successfulModels) {
    if (result.mediaBytes === undefined) continue;
    const stored = await encryptAndStoreMedia({
      mediaStorage,
      epochPublicKey,
      conversationId,
      modelId,
      assistantMsgId: getAssistantId(modelId),
      mediaBytes: result.mediaBytes,
      mimeType: result.mimeType,
      width: result.width,
      height: result.height,
      durationMs: result.durationMs,
      pricing: pricingFor(modelId, result),
    });
    assistantMessages.push(stored.assistantMessage);
    downloadUrls.set(stored.contentItemId, stored.downloadUrl);
  }

  return { assistantMessages, downloadUrls };
}

// ---------------------------------------------------------------------------
// executeMediaPipeline — shared image/video/audio orchestrator
// ---------------------------------------------------------------------------

interface ExecuteMediaPipelineDeps {
  /**
   * Writes the SSE error when every model in the batch failed. Injected to
   * keep this module independent of stream-pipeline.ts (which owns the text
   * pipeline's analogous helper).
   */
  writeFirstMediaError: (
    mediaResults: Map<string, MediaStreamResult>,
    writer: SSEEventWriter,
    noContentMessage: string
  ) => Promise<void>;
  handleBillingResult: (options: {
    c: Context<AppEnv>;
    billingPromise: Promise<SaveChatTurnResult>;
    assistantMessageId: string;
    userId: string;
    senderId: string;
    model: string;
    generationId: string | undefined;
  }) => Promise<SaveChatTurnResult | null>;
  broadcastAndFinish: (options: {
    c: Context<AppEnv>;
    conversationId: string;
    userMessageId: string;
    assistantMessageId: string;
    billingResult: SaveChatTurnResult;
    writer: SSEEventWriter;
    modelName?: string;
  }) => Promise<void>;
  createAssistantIdLookup: (models: string[]) => (modelId: string) => string;
}

/**
 * Shared pipeline for image/video/audio generation.
 * Fans out per-model inference, encrypts results, stores in R2, persists,
 * attaches presigned download URLs to the SSE done event.
 */
export function executeMediaPipeline(
  input: MediaPipelineInput,
  deps: ExecuteMediaPipelineDeps
): Response {
  const {
    c,
    conversationId,
    models,
    userMessage,
    prompt,
    billingUserId,
    groupBudget,
    memberContext,
    releaseReservation,
    senderId,
    forkId,
    parentMessageId,
    pricingFor,
    buildRequest,
    noContentErrorMessage,
  } = input;
  const db = c.get('db');
  const aiClient = c.get('aiClient');
  const mediaStorage: MediaStorage = c.get('mediaStorage');

  const getAssistantId = deps.createAssistantIdLookup(models);

  const primaryModel = models[0];
  if (!primaryModel) throw new Error('invariant: models must have at least one entry');

  broadcastFireAndForget(
    c.env,
    conversationId,
    createEvent('message:new', {
      messageId: userMessage.id,
      conversationId,
      senderType: 'user',
      senderId,
      content: prompt,
    }),
    safeExecutionCtx(c)
  );

  const streamEntries: MediaModelStreamEntry[] = models.map((modelId) => ({
    modelId,
    assistantMessageId: getAssistantId(modelId),
    stream: aiClient.stream(buildRequest(modelId)),
  }));

  return streamSSE(c, async (stream) => {
    const writer = createSSEEventWriter(stream);
    // SSE keep-alive heartbeat so a slow video generation (>90s with no events
    // between `model:media:start` and `done`) still resets the client's
    // STREAM_TIMEOUT_MS timer. Per the SSE spec, lines beginning with `:` are
    // comments and are dropped by EventSource consumers — but the bytes are
    // delivered to the underlying ReadableStream reader, which is what the
    // client's `readWithTimeout` watches.
    const keepAliveTimer = setInterval(() => {
      // Fire-and-forget write. After abort the underlying writer rejects;
      // swallow the rejection — the next typed write via `writeIfConnected`
      // observes the disconnection through the `onAbort` callback.
      void writeKeepAliveSafe(stream);
    }, KEEPALIVE_INTERVAL_MS);
    try {
      await writer.writeStart({
        userMessageId: userMessage.id,
        models: models.map((modelId) => ({
          modelId,
          assistantMessageId: getAssistantId(modelId),
        })),
      });

      const mediaResults = await collectMultiMediaModelStreams(streamEntries, writer);
      const successfulModels = filterSuccessfulMediaModels(mediaResults);

      if (successfulModels.length === 0) {
        await deps.writeFirstMediaError(mediaResults, writer, noContentErrorMessage);
        return;
      }

      const [conv] = await db
        .select({ currentEpoch: conversations.currentEpoch })
        .from(conversations)
        .where(eq(conversations.id, conversationId));
      const currentEpoch = conv?.currentEpoch ?? 1;
      const { epochPublicKey } = await fetchEpochPublicKey(db, conversationId, currentEpoch);

      const { assistantMessages, downloadUrls } = await processMediaResults({
        mediaStorage,
        epochPublicKey,
        conversationId,
        pricingFor,
        getAssistantId,
        successfulModels,
      });

      const groupBillingContext = buildGroupBillingContext(memberContext, groupBudget);
      const billingPromise = saveChatTurn(db, {
        userMessageId: userMessage.id,
        userContent: userMessage.content,
        conversationId,
        userId: billingUserId,
        senderId,
        assistantMessages,
        ...(groupBillingContext !== undefined && { groupBillingContext }),
        parentMessageId,
        ...(forkId !== undefined && { forkId }),
      });

      const billingResult = await deps.handleBillingResult({
        c,
        billingPromise,
        assistantMessageId: getAssistantId(primaryModel),
        userId: billingUserId,
        senderId,
        model: primaryModel,
        generationId: mediaResults.get(primaryModel)?.generationId,
      });

      if (billingResult) {
        attachDownloadUrls(billingResult, downloadUrls);
        await deps.broadcastAndFinish({
          c,
          conversationId,
          userMessageId: userMessage.id,
          assistantMessageId: getAssistantId(primaryModel),
          billingResult,
          writer,
          modelName: primaryModel,
        });
      } else {
        await writer.writeError({
          message: 'Failed to save message',
          code: ERROR_CODE_BILLING_ERROR,
        });
      }
    } finally {
      clearInterval(keepAliveTimer);
      await releaseReservation();
    }
  });
}
