import { LEGAL_CONTACT_EMAIL, RELEASE_STAGE } from '../constants.ts';
import {
  MEDIA_STORAGE_COST_PER_BYTE,
  STORAGE_COST_PER_1K_CHARS,
  TOTAL_FEE_RATE,
} from '../affordability/constants.ts';
import { FEE_CATEGORIES, formatFeePercent } from '../affordability/money/fees.ts';
import { termsOfServiceEffectiveDate } from './effective-dates.ts';
import type { LegalSection, LegalDocumentMeta } from './types.ts';

export const TERMS_OF_SERVICE_META: LegalDocumentMeta = {
  title: 'Terms of Service',
  // Resolved on access rather than assigned here: `./effective-dates.ts` states why the
  // read cannot happen when this module loads.
  get effectiveDate(): string {
    return termsOfServiceEffectiveDate();
  },
  contactEmail: LEGAL_CONTACT_EMAIL,
};

const totalFeePercent = formatFeePercent(TOTAL_FEE_RATE);
const feeBreakdownClause = FEE_CATEGORIES.map(
  (category) => `${formatFeePercent(category.rate)} ${category.label}`
).join(', ');
// Skip the breakdown bullet entirely when no fee category has a positive rate,
// to avoid rendering a malformed "Fee breakdown: ." sentence.
/* v8 ignore next -- @preserve defensive empty-arm: FEE_CATEGORIES is non-empty for every configuration with a positive fee rate; the `[]` arm guards an all-zero-rate config that does not currently exist */
const feeBreakdownBullets =
  FEE_CATEGORIES.length > 0 ? [`Fee breakdown: ${feeBreakdownClause}.`] : [];
const storageCostPer1k = `$${String(STORAGE_COST_PER_1K_CHARS)}`;
// The published media price is per DECIMAL megabyte, a million bytes. The binary reading of the
// same per-byte rate quotes a figure about five percent higher, so the unit is part of the price
// a reader is quoted, not a rendering choice: `mediaStorageNanoUsd` and the per-megabyte figures
// in `../affordability/constants.ts` are already read this way.
const BYTES_PER_MEGABYTE = 1_000_000;
const mediaCostPerMegabyte = `$${String(MEDIA_STORAGE_COST_PER_BYTE * BYTES_PER_MEGABYTE)}`;

export const TERMS_BETA_SECTION: LegalSection = {
  id: 'beta',
  title: 'Open Beta',
  simplyPut:
    'HushBox works, and it is still changing fast. Here is exactly what that means, and what never changes.',
  points: [
    'HushBox is in open beta. Features will change, move, or go away for good, sometimes without notice.',
    'There will be downtime, planned and unplanned, including while we ship updates.',
    'An update can cut off a reply while it is being written.',
    'You may be signed out after an update, and the app will ask you to refresh or update often.',
    'Expect bugs, including in what the app displays. You can report them with Send feedback in the app.',
    'What never changes, beta or not: we cannot read your messages, and the beta changes nothing in the Privacy Policy.',
    'Your purchased credit is never lost to our mistakes. If a defect or a restore affects your balance, we put it back.',
    'Your rights under consumer protection law still apply. Nothing in this section limits them.',
    'The beta will end. When it ends, this section will be removed from these terms.',
  ],
};

const STANDING_TERMS_SECTIONS: readonly LegalSection[] = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    simplyPut: 'Using HushBox means you agree to these terms.',
    points: [
      'By creating a HushBox account or using the service, you agree to be bound by these Terms of Service.',
      'If you do not agree to these terms, do not use HushBox.',
      'Your continued use of the service constitutes ongoing acceptance.',
    ],
  },
  {
    id: 'eligibility',
    title: 'Who Can Use HushBox',
    simplyPut: 'You must be 13 or older, and older where your local law sets a higher age.',
    points: [
      'You must be at least 13 years old to use HushBox. If the law where you live sets a higher age for agreeing to online services on your own, you must be at least that age.',
      'If you are under 18, you confirm that a parent or guardian has agreed to these terms for you.',
    ],
  },
  {
    id: 'description',
    title: 'Description of Service',
    simplyPut:
      'Chat with many AI models in one app, with your conversations stored encrypted. The mobile apps update directly from us and may require an update to keep working.',
    points: [
      'HushBox is an AI chat application that provides access to multiple AI models through a unified interface.',
      'Responses are generated by third-party AI providers. HushBox routes your requests and stores your conversations in encrypted form.',
      'HushBox measures its own public website. What is counted and what is kept are described in the Privacy Policy.',
      'The HushBox apps for iOS and Android download updates to their interface directly from us, outside the app stores. When an update is required, the app asks you to apply it before you can keep using it.',
      'HushBox is not a professional advisor, therapist, lawyer, or medical provider. The service is subject to availability.',
    ],
  },
  {
    id: 'account-responsibilities',
    title: 'Account Responsibilities',
    simplyPut: 'Keep your password safe. We can\u2019t recover it.',
    points: [
      'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.',
      'Your password is never stored on our servers. If you lose your password and your recovery phrase, your encrypted data cannot be recovered by anyone, including HushBox.',
      'You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account.',
    ],
  },
  {
    id: 'acceptable-use',
    title: 'Acceptable Use',
    simplyPut: 'Don\u2019t use HushBox for anything illegal or harmful.',
    points: [
      'You agree not to use HushBox to generate illegal content, extract harmful information, deceive or defraud others, or engage in any activity that violates applicable law.',
      'You agree not to reverse engineer, decompile, or disassemble any part of the service.',
      'Automated access or bot usage is not permitted without prior written permission from HushBox.',
      'We reserve the right to suspend or terminate accounts that violate this policy.',
    ],
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property',
    simplyPut:
      'Your inputs are yours. We\u2019ll never claim your AI outputs. Feedback you send us, we may use freely.',
    points: [
      'The HushBox application, brand, and source code are the property of LOME-AI LLC.',
      'Your inputs (messages you send) belong to you.',
      'HushBox will never claim ownership of any AI-generated output. You are free to use AI responses as you see fit.',
      'Note that AI-generated outputs may not be copyrightable under current law. This is an evolving area of law and is outside HushBox\u2019s control.',
      'If you send us feedback or suggestions, we may use them to improve HushBox without owing you anything for them.',
    ],
  },
  {
    id: 'ai-disclaimer',
    title: 'AI Content Disclaimer',
    simplyPut: 'AI can be wrong. Don\u2019t bet your life on it.',
    points: [
      'AI-generated responses may be inaccurate, incomplete, biased, or entirely fabricated. You should independently verify any information received through the service.',
      'Do not rely on AI responses for medical, legal, financial, or safety-critical decisions.',
      'HushBox is not liable for any actions you take based on AI-generated content.',
    ],
  },
  {
    id: 'third-party-services',
    title: 'Third-Party Services',
    simplyPut: 'We depend on AI providers. Their availability affects ours.',
    points: [
      'HushBox relies on third-party AI providers to generate responses. The availability, quality, and behavior of these providers is outside our control.',
      'We are not responsible for changes to third-party provider policies, pricing, or service availability.',
      'Model availability may change without notice as providers update their offerings.',
    ],
  },
  {
    id: 'payment-terms',
    title: 'Payment Terms',
    simplyPut: `Pay for what you use. A ${totalFeePercent} fee on model usage, ${storageCostPer1k} per 1,000 characters stored, and ${mediaCostPerMegabyte} per megabyte (a million bytes) of media stored. Model prices are references and can vary with the provider that serves a reply. No hidden charges.`,
    points: [
      `HushBox operates on a pay-as-you-go basis. A ${totalFeePercent} fee is applied to all AI model usage.`,
      ...feeBreakdownBullets,
      `A storage fee of ${storageCostPer1k} per 1,000 characters is charged for storing your conversations.`,
      `A storage fee of ${mediaCostPerMegabyte} per megabyte (a million bytes) is charged for storing the images, audio, and video you generate.`,
      'Model prices shown in HushBox, and any estimate of what a message will cost, are references rather than exact quotes. A reply can cost more or less than shown, for example when a different provider serves it, or when a long conversation moves a model to its higher long-conversation rate. The fee percentage and storage prices in these terms do not vary from reply to reply. Before a reply starts, we reserve an amount to cover it. If the reply costs more than that amount, we still charge its full cost.',
      `All purchases are final. If you believe a charge was made in error, contact ${LEGAL_CONTACT_EMAIL} within 30 days.`,
      `If you live in the European Union or the United Kingdom, you can cancel a credit purchase within 14 days of making it by emailing ${LEGAL_CONTACT_EMAIL}, and we will refund the credit that remains. Credit you have already used is not refunded.`,
    ],
  },
  {
    id: 'limitation-of-liability',
    title: 'Limitation of Liability',
    simplyPut: 'Our liability is capped at what you\u2019ve paid us.',
    points: [
      'To the maximum extent permitted by law, HushBox\u2019s total liability to you is limited to the fees you have paid to HushBox in the 12 months preceding the claim.',
      'HushBox is not liable for any indirect, incidental, consequential, special, or punitive damages.',
    ],
  },
  {
    id: 'warranties',
    title: 'Disclaimer of Warranties',
    simplyPut: 'The service is provided as-is.',
    points: [
      'HushBox is provided "as is" and "as available" without warranties of any kind, whether express or implied.',
      'We do not guarantee the accuracy, completeness, or reliability of AI-generated content, the availability or uninterrupted operation of the service, or fitness for any particular purpose.',
    ],
  },
  {
    id: 'indemnification',
    title: 'Indemnification',
    simplyPut: 'If your misuse gets us sued, you cover the cost.',
    points: [
      'If someone brings a claim against LOME-AI LLC because you broke these terms or the law while using HushBox, you agree to cover the resulting losses, including reasonable legal fees.',
      'This applies only as far as the law where you live allows.',
    ],
  },
  {
    id: 'termination',
    title: 'Termination',
    simplyPut:
      'You can leave anytime, including permanently deleting your account. We can terminate for violations.',
    points: [
      'You may delete your account at any time from your Settings page.',
      'You may stop using HushBox without deleting your account; we keep your encrypted data while your account exists.',
      'HushBox may suspend or terminate your account if you violate these Terms of Service.',
      'Upon termination by either side, certain provisions survive, including Limitation of Liability, Intellectual Property, Disclaimer of Warranties, Indemnification, and Governing Law.',
    ],
  },
  {
    id: 'governing-law',
    title: 'Governing Law',
    simplyPut: 'Indiana law applies.',
    points: [
      'These terms are governed by the laws of the State of Indiana, United States, without regard to conflict of law principles.',
      'Any disputes arising from these terms or your use of HushBox shall first be attempted to be resolved informally. If informal resolution fails, disputes shall be resolved in the state courts of Indiana.',
      'You agree to waive any right to participate in a class action lawsuit or class-wide arbitration against HushBox.',
    ],
  },
  {
    id: 'app-stores',
    title: 'App Stores',
    simplyPut:
      'Your app store\u2019s terms also cover the download. Apple and Google are not parties to these terms.',
    points: [
      'If you downloaded HushBox from the App Store or Google Play, that store\u2019s own terms also apply to the download.',
      'Apple and Google are not parties to these terms and are not responsible for HushBox or its content.',
    ],
  },
  {
    id: 'general',
    title: 'General',
    simplyPut:
      'Consumer-law rights still apply. If a court strikes one term the rest stand, and these terms plus the Privacy Policy are the whole agreement.',
    points: [
      'Nothing in these terms takes away a right you have under consumer protection law that a contract cannot waive.',
      'If a court finds part of these terms unenforceable, the rest stay in effect.',
      'These terms and the Privacy Policy are the whole agreement between you and LOME-AI LLC about HushBox.',
      'You may not transfer your account or these terms to anyone else. We may transfer them to a company that takes over HushBox, and we will email you if we do.',
      'We are not responsible for a failure caused by events outside our reasonable control, such as an outage at a provider we rely on.',
      'If we do not enforce part of these terms at some point, we keep the right to enforce it later.',
      `Questions about these terms: ${LEGAL_CONTACT_EMAIL}. LOME-AI LLC, Indiana, United States.`,
    ],
  },
  {
    id: 'changes',
    title: 'Changes to Terms',
    simplyPut: 'Changes are effective when posted.',
    points: [
      'We may modify these Terms of Service at any time. Changes are effective when posted on this page.',
      'Your continued use of HushBox after changes are posted constitutes your acceptance of the updated terms.',
    ],
  },
];

// Published legal text: frozen so no importer can rewrite what the site serves. The freeze
// backs a readonly declared type, which rejects a static mutation before it can run.
for (const section of [...STANDING_TERMS_SECTIONS, TERMS_BETA_SECTION]) {
  Object.freeze(section.points);
  Object.freeze(section);
}

/** The Terms as published under `stage`: the beta section follows the service description. */
export function termsSectionsFor(stage: 'beta' | 'stable'): readonly LegalSection[] {
  const sections =
    stage === 'beta'
      ? STANDING_TERMS_SECTIONS.flatMap((section) =>
          section.id === 'description' ? [section, TERMS_BETA_SECTION] : [section]
        )
      : [...STANDING_TERMS_SECTIONS];
  return Object.freeze(sections);
}

export const TERMS_SECTIONS: readonly LegalSection[] = termsSectionsFor(RELEASE_STAGE);
