/**
 * Where the turn producer's runnable set for the Smart slot is one candidate
 * whose provider cap and context never bind, the slot's composer budget is what
 * a named row at that candidate's price funds, long-context rates included.
 */

import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { PREMIUM_RECENCY_MS } from '../money/premium.ts';
import { nanoUSD } from '../money/nano-usd.ts';
import { poolModelFromWire } from '../model/wire-pool-row.ts';
import { pricingToWire } from '../price/wire.ts';
import { getTurnOptions } from '../turn/turn-options.ts';
import { tokenPricingFixture } from '../../testing/pricing-fixture.ts';
import { textTurnBudget } from './text-turn-budget.ts';
import type { Model } from '../../schemas/api/models.ts';

/** Larger than any answer the generated funding buys, so neither cap binds. */
const UNBINDING = 100_000_000;

function servedRow(id: string, pricing: Model['pricing'], isSmartModel = false): Model {
  return {
    id,
    name: id,
    provider: 'vendor',
    modality: 'text',
    contextLength: UNBINDING,
    maxOutputTokens: UNBINDING,
    pricing,
    description: 'a text model',
    supportedParameters: [],
    created: 0,
    ...(isSmartModel ? { isSmartModel: true } : {}),
  };
}

/** One candidate, with an optional long-context rate, and a turn's prompt and funding. */
const singleCandidateArb = fc
  .record({
    input: fc.bigInt({ min: 1n, max: 1_000_000n }),
    output: fc.bigInt({ min: 1n, max: 1_000_000n }),
    tier: fc.option(
      fc.record({
        abovePromptTokens: fc.integer({ min: 1, max: 400_000 }),
        rise: fc.bigInt({ min: 0n, max: 1_000_000n }),
      })
    ),
    promptChars: fc.integer({ min: 1, max: 900_000 }),
    inputShare: fc.double({ min: 0, max: 1, noNaN: true }),
    spendable: fc.bigInt({ min: 0n, max: 100_000_000_000n }),
  })
  .map(({ input, output, tier, promptChars, inputShare, spendable }) => ({
    pricing: tokenPricingFixture({
      input,
      output,
      tiers:
        tier === null
          ? []
          : [
              {
                abovePromptTokens: tier.abovePromptTokens,
                input: input + tier.rise,
                output: output + tier.rise,
              },
            ],
    }),
    promptChars,
    inputChars: Math.floor(promptChars * inputShare),
    spendable,
  }));

describe('the Smart slot’s budget, generated by singleCandidateArb', () => {
  it('equals what a named row at the one candidate’s price funds', () => {
    fc.assert(
      fc.property(singleCandidateArb, ({ pricing, promptChars, inputChars, spendable }) => {
        const candidate = servedRow('vendor/candidate', pricingToWire(pricing));
        const smart = servedRow('smart-model', pricingToWire(pricing), true);
        const poolModel = poolModelFromWire(candidate);
        if (poolModel === undefined) throw new Error('expected the candidate to price');
        const turnOptions = getTurnOptions(
          {
            spendableNanoUsd: nanoUSD(spendable),
            heldNanoUsd: nanoUSD(0n),
            payerTier: 'paid',
            payer: 'self',
          },
          {
            systemChars: 0,
            instructionChars: 0,
            historyChars: promptChars - inputChars,
            inputChars,
            attachmentBytes: 0,
          },
          {
            answerSources: { models: [], smartSlot: true },
            modality: 'text',
            pinned: {},
            webSearch: false,
          },
          { models: [poolModel], nowMs: PREMIUM_RECENCY_MS }
        );
        const common = {
          promptChars,
          inputChars,
          payerTier: 'paid' as const,
          payerSpendableNanoUsd: spendable,
          webSearch: false,
          loopEffort: undefined,
          reasoningBudgetTokens: 0,
        };

        expect(textTurnBudget({ ...common, models: [smart], turnOptions })?.maxOutputTokens).toBe(
          textTurnBudget({ ...common, models: [candidate], turnOptions: undefined })
            ?.maxOutputTokens
        );
      })
    );
  });
});
